---
 - name: Add app servers IP address to frontends /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*db$'
    line: "{{  hostvars[ groups.app[0] ].ansible_host }} {{ groups.app[0] }}"
    line: "{{  hostvars[ groups.app[1] ].ansible_host }} {{ groups.app[1] }}"
    state: present

  - name: Install {{ payload }}
    yum:
      name: "{{ payload }}"
      #disablerepo: "internal.repo"
      state: present
  - name: Update haproxy.cfg from template
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: start {{ payload }}

