---
  - name: Add app1 servers IP address to frontends /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*app$'
      line: "{{ hostvars[ groups.apps[0] ].ansible_host }} {{ groups.apps[0] }}"
      state: present

  - name: Add app2 servers IP address to frontends /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*app$'
      line: "{{ hostvars[ groups.apps[1] ].ansible_host }} {{ groups.apps[1] }}"
      state: present

  - name: Install "{{ payload }}"
    yum:
      name: "{{ payload }}"
      state: present

  - name: Update haproxy.cfg from template
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: start {{ payload }}

