---

# tasks file for osp.servers
- name: Create server instance
  os_server:
    cloud: openstack
    name: db
    state: present
    image: rhel-guest
    flavor: m1.medium
    key_name: ansible_ssh
    wait: yes
    security_groups: db
    delete_fip: true
    meta: group=db, deployment_name=QA
    nics:
      - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  register: r_instance


- name: Wait for async OSP instance creation to complete
  async_status: "jid={{ item.ansible_job_id }}"
  register: r_wait
  until: r_wait.finished
  retries: 900
  loop: "{{ r_instance.results }}"


- when: openstack_server_state != 'absent' | default(true)
  block:
    - name: Add floating IP to instances
      os_floating_ip:
        cloud: openstack
        state: present
        reuse: yes
        server: db
        network: ext_network
        wait: true
        timeout: 180
      register: r_floating_ip
        msg: "db Public IP address = {{ r_floating_ip }}"

    - name: Wait for servers by name to be available
      wait_for:
        host: "{{ r_floating_ip.floating_ip.floating_ip_address }}"
        port: 22
        search_regex: OpenSSH
        timeout: 600
      delegate_to: "{{ inventory_hostname }}"
