---
- name: Add db IP address to app servers /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*db$'
#    line: "{{ groups.appdbs[0].ansible_host }} {{ groups.appdbs[0] }}"
# HArdcoding until I workout the inventory reference for public ip address
    line: "{{ 192.0.2.194 }} {{ groups.appdbs[0] }}"
#    line: "{{ groups.appdbs[0].ansible_host }} {{ groups.appdbs[0] }}"
    state: present

- name: Install Tomcat
  yum:
    name: "{{ payload }}"
    state: latest

- name: Ensure "{{ payload }}" web root directory exists
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory

- name: Update tomcat index.html from template
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
  notify: start {{ payload }}

